runtime: python310
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  AZURE_CLIENT_ID: "your-client-id"  # Azure Client ID for login
  AZURE_TENANT_ID: "your-tenant-id"  # Azure Tenant ID for login
  AZURE_CLIENT_SECRET: "your-client-secret"  # Azure Client Secret for login

instance_class: F2

handlers:
  - url: /static
    static_dir: static  # Static files (CSS, images, JS) will be served from the static folder
  - url: /.*
    script: auto
